12

dataset:	 id12_hmeq_p.sas7bdat

metadata information:	 id12_hmeq_meta.csv

fail in:	 id12_hmeq_p.sas7bdat
Traceback (most recent call last):
  File "/root/atoml/automl/runbench.py", line 155, in runbenchmark
    data,X,y,X_train, y_train,X_test, y_test = prep(dataset,dirt,nfeatures,cfeatures,target,delim=',',indexdrop=False)
TypeError: 'bool' object is not callable
