['id0_autoinsurance_claims_p.sas7bdat', 'id1_claim_history_p.sas7bdat', 'id2_cust_cibc_sas2_p.sas7bdat', 'id3_donor_raw_data3_p.sas7bdat', 'id4_home_prices_p.sas7bdat', 'id5_solarfarm_p.sas7bdat', 'id6_uci_abalone_p.sas7bdat', 'id7_uci_winequality_p.sas7bdat'] ['id0_autoinsurance_claims_meta.csv', 'id1_claim_history_meta.csv', 'id2_cust_cibc_sas2_meta.csv', 'id3_donor_raw_data3_meta.csv', 'id4_home_prices_meta.csv', 'id5_solarfarm_meta.csv', 'id6_uci_abalone_meta.csv', 'id7_uci_winequality_meta.csv']
4

dataset:	 id4_home_prices_p.sas7bdat

metadata information:	 id4_home_prices_meta.csv
Traceback (most recent call last):
  File "autoreg.py", line 106, in <module>
    runbenchmark(prep,dataset,framework,foldlist,ncore,timelist,dirt,meta,fitmetrics,rep,logfile,task_token)
NameError: name 'fitmetrics' is not defined
Failed:	 id4 id4_home_prices_p.sas7bdat
5

dataset:	 id5_solarfarm_p.sas7bdat

metadata information:	 id5_solarfarm_meta.csv
Traceback (most recent call last):
  File "autoreg.py", line 106, in <module>
    runbenchmark(prep,dataset,framework,foldlist,ncore,timelist,dirt,meta,fitmetrics,rep,logfile,task_token)
NameError: name 'fitmetrics' is not defined
Failed:	 id5 id5_solarfarm_p.sas7bdat
6

dataset:	 id6_uci_abalone_p.sas7bdat

metadata information:	 id6_uci_abalone_meta.csv
Traceback (most recent call last):
  File "autoreg.py", line 106, in <module>
    runbenchmark(prep,dataset,framework,foldlist,ncore,timelist,dirt,meta,fitmetrics,rep,logfile,task_token)
NameError: name 'fitmetrics' is not defined
Failed:	 id6 id6_uci_abalone_p.sas7bdat
7

dataset:	 id7_uci_winequality_p.sas7bdat

metadata information:	 id7_uci_winequality_meta.csv
Traceback (most recent call last):
  File "autoreg.py", line 106, in <module>
    runbenchmark(prep,dataset,framework,foldlist,ncore,timelist,dirt,meta,fitmetrics,rep,logfile,task_token)
NameError: name 'fitmetrics' is not defined
Failed:	 id7 id7_uci_winequality_p.sas7bdat
